package probs;

import utils.euler.EulerProblem;

/**
 * Project Euler problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * 
 * @author Lord Torgamus
 */
public class Problem0002 extends EulerProblem {
    public static void main(String[] args) {
        run(new Problem0002());
    }

    @Override
    protected long doProblemSpecificStuff() {
        int total = 0;
        int fibLower = 0;
        int fibHigher = 1;
        int nextFib = fibLower + fibHigher;

        do {
            if(nextFib % 2 == 0) {
                total += nextFib;
            }

            fibLower = fibHigher;
            fibHigher = nextFib;
            nextFib = fibLower + fibHigher;
        } while(nextFib <= 4000000);

        return total;
    }
}
